---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: ckad-practice-workshop
spec:
  title: CKAD Practice
  description: A port of Liptan Biswas' CKAD practice challenge
  vendor: kube.academy
  difficulty: beginner
  duration: 15m
  url: https://github.com/eitansuez/lab-ckad-practice
  content:
    files: github.com/eitansuez/lab-ckad-practice
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
      examiner:
        enabled: true