#!/bin/bash

set -euo pipefail

kubectl get po mp-hello -o jsonpath='{.spec.containers[*].image}' | grep -w kubectl | grep -w nginx | grep -w 'consul'
kubectl exec mp-hello -c $(kubectl get po mp-hello -o jsonpath='{.spec.containers[?(@.image==\"kubectl\")].name}') -- sh -c 'ps | grep -v grep | grep sleep'
