#!/bin/bash

k apply -f /home/eduk8s/mypodx.yaml --dry-run=server -o jsonpath='{.kind}' | grep -q -w 'Pod'
k apply -f /home/eduk8s/mypodx.yaml --dry-run=server -o jsonpath='{.spec.containers[0].image}' | grep -q -w 'redis'
k apply -f /home/eduk8s/mypodx.yaml --dry-run=server -o jsonpath='{.metadata.name}' | grep -q -w 'mypodx'